name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ] # Ejecuta el workflow cuando haya cambios en la rama "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./landing-sauren

      - name: Build project
        run: npm run build
        working-directory: ./landing-sauren

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./landing-sauren/dist
          cname: www.sauren.ar
